#!/bin/bash

## A script to record the temperature and humidity measured by a DHT22 sensor.
## It registers a row of the form "(timestamp,temperature(C),humidity(%))"


########## VARIABLES

#temp=${registro.txt::}

now=$(date +"%x")

min=$(date +"%M")
hour=$(date +"%H")
sec=$(date +"%S")

timestamp=$(date +"%Y-%m-%d_%H:%M:%S")

########## SCRIPT

echo "$timestamp $(sudo ./AdafruitDHT.py 22 4)" >> registro.txt

echo "$timestamp"

