#!/bin/bash

## A script to record the temperature and humidity measured by a DHT22 sensor.
## It registers a row of the form "(date,hour,min,sec,temperature(C),humidity(%))"


########## VARIABLES

#temp=${registro.txt::}

now=$(date +"%x")

min=$(date +"%M")
hour=$(date +"%H")
sec=$(date +"%S")

########## SCRIPT

echo "$now $hour $min $sec $(sudo ./AdafruitDHT.py 22 4)" >> registro.txt

echo "the second is $sec"

